[build]
  # Netlify will automatically detect and build Go functions
  # No custom build command needed for Go functions
  command = ""
  publish = ""

[build.environment]
  # Set Go version for the build environment
  GO_VERSION = "1.21"

# Redirect configuration to route the JWKS endpoint
[[redirects]]
  # Route /oauth/discovery/keys to the serverless function
  from = "/oauth/discovery/keys"
  to = "/.netlify/functions/keys"
  status = 200

# Additional redirect for trailing slash handling
[[redirects]]
  from = "/oauth/discovery/keys/"
  to = "/.netlify/functions/keys"
  status = 200

# CORS and security headers for all responses
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers for API access
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Specific headers for the JWKS endpoint
[[headers]]
  for = "/oauth/discovery/keys"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"
    Access-Control-Allow-Origin = "*"